using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NodeV2
{
    //Grid position relative to the array
    public int GridX;
    public int GridY;
    //For checking if its a wall could also be
    //a layermask instead if extra variables should be included
    public bool IsAWall;
    //Transform position of the node in the scene
    public Vector3 NodePosition;
    //Prior Node used for the grid 
    public NodeV2 Parent;
    //Various prices of traveling across node to node direction and diagonal 
    public int gCost;
    public int hCost;

    public int FCost { get { return gCost + hCost; } }
    //Constructor class for the node as
    //there will be many nodes generated by the grid class
    public NodeV2(bool wall, Vector3 pos,int igridx,int igridy)
    {
        this.IsAWall = wall;
        this.GridX = igridx;
        this.GridY = igridy;
        this.NodePosition = pos;
    }
}
